apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: wte586-default
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  type: ClusterIP
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31883
  selector:
    app: mosquitto
